### ISSUE TITLE
Make guides directory 

### ISSUE THREAD

**Issue by zoelogic** [inno-code/simplephp#13]
In the simplephp root directory put a folder named `./guides`. In this directory we will make md files (md stands for Mark Down). These files will guide people through doing common things like `git` `komodo` `lamp install` and other things.  So, Let's move the guide notes @taono wrote in #11 into the guides folder. 
- In the .md files we want to use git-hub's mark down language.  Notice when you write comments in a github issue there are "Write" and "Preview" tabs above on the left. Look to the write of those tabs and you will see a "Markdown supported" link. Click that link and read the mark down notes to see how to beautify your mark down files.  When I write comments I uses this Markdown language to make bullet points, quotes, or add code. Everyone should begin using the Markdown.
  https://guides.github.com/features/mastering-markdown/

**Comment by taono** [comment]
## working on it

@papanja @natkre feel free to check [git documentation](http://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell) for creating **a folder on simplephp root directory** through command line.

**Comment by taono** [comment]
## Four Hours Later...

So, @zoelogic ,I didn't figure out a way to create guides directory. Here's my attempt process. Please help to correct my steps of thinking bellow and provide a correct answer. 
1. In order to create a folder on inno-code/simplephp , i need to clone inno-code/simplephp first. 
2. after clone the repo, I need to create guides folder at simplephp root directory. 
3. after creating guides folder, I created a md file just to fill empty guides folder ( less git won't show empty folder after push). 
4. branch checkout to origin master https://github.com/inno-code/simplephp (I'm so stuck here. bash keeps telling me the directory is not found). 
5. after check out to inno-code/simplephp branch, add, commit, and push to git. 
6. there shall be a pull request under inno-code/simplephp after push. The final step is to merge. 

So, I thought the above steps would work theoretically. But I'm stuck on step 4. Also, I try to add file on git wesite. But it only allows to add file but not folder. I've been working on it for four + hours literally, feeling pretty unfruitful.

**Comment by zoelogic** [comment]
- You do not need to clone the project.  You already forked that repo and cloned that fork into your local computer.
  Just need to make the folder and files.  Then,
  - `git add .`
  - `git commit`
  - `git log`  shows the commit you just made
- After working on your project and committing all changes.  
  - `git fetch`  will fetch the state of the remote repo.
  - `git status` if another user added new content to remote this will tell you how
    many commits behind your local repo is from the the remote repo.
  - `git pull` if your local repo is behind remote. This will pull remote commits into your local repo.  
    If there are merge conflicts you will have to resolve them.
  - `git push`  after pulling remote repo state into your project (synching project up to remote)
    you can push your new work back to the remote. 

Note: You only clone when you do not have a repo on your local computer yet.
